apiVersion: v1
kind: Service
metadata:
  name: eriauth
spec:
  type: ClusterIP
  clusterIP: 10.96.46.124
  selector:
    app: eriauth
  externalIPs:
    - 10.111.131.125
  ports:
    - targetPort: 46469
      port: 46469
