apiVersion: apps/v1
kind: Deployment
metadata:
  name: eriauth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eriauth
    spec:
      containers:
        - name: eriauth
          image: eribyteofficial/eriauth
          imagePullPolicy: Always
          ports:
            - containerPort: 46469
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: APP_ID
              valueFrom:
                configMapKeyRef:
                  name: eriauth-secrets
                  key: APP_ID
            - name: CRUD_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: eriauth-secrets
                  key: CRUD_PASSWORD
            - name: APP_SECRET
              valueFrom:
                configMapKeyRef:
                  name: eriauth-secrets
                  key: APP_SECRET
  selector:
    matchLabels:
      app: eriauth